### ISSUE TITLE
Adding Resources 

### ISSUE THREAD

**Issue by FallenDeity** [PokeAPI/cries#1]
So this repository is for storing the cries right @Naramsim following conventions of the sprites repository

**Comment by Naramsim** [comment]
yes, as described in the comment I made on the other issue you opened a while ago

**Comment by FallenDeity** [comment]
@Naramsim does the content format seem fine?

**Comment by Naramsim** [comment]
Perfect! We can now add this repo as a submodule to the pokeapi one and start build the API

**Comment by Naramsim** [comment]
Hi, I added the repo as submodule to pokeapi

**Comment by FallenDeity** [comment]
oh rip i already did that locally no issues I'll just pull the changes, I'll test out the changes in the api and make a pr by tomorrow i suppose been a bit busy past few days

**Comment by FallenDeity** [comment]
Completed with pr [#1030](https://github.com/PokeAPI/pokeapi/pull/1030)
